// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Tooling
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidToolingPackageString = "5594ee3b-1ff9-4b15-b5db-ed7864223937";
        public static Guid guidToolingPackage = new Guid(guidToolingPackageString);

        public const string guidToolingPackageCmdSetString = "b06e81b0-3ef8-4c81-b260-412cd82b7366";
        public static Guid guidToolingPackageCmdSet = new Guid(guidToolingPackageCmdSetString);

        public const string guidImagesString = "dfda9d4e-d782-47e1-9565-f7d36eaf6c08";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ProjectContextMenuGroup = 0x2000;
        public const int MainGroup = 0x2001;
        public const int TopGroup = 0x2002;
        public const int TopWindowsGroup = 0x2003;
        public const int MainMenu = 0x3001;
        public const int TopMenu = 0x3002;
        public const int TopWindowsMenu = 0x3003;
        public const int cmdidOpenProjectMoverCommand = 0x1021;
        public const int cmdidRenameProjectCommand = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}